SELECT *FROM Countries
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Albania', 'AL' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Algeria', 'DZ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('American Samoa', 'AS' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Andorra', 'AD' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Angola', 'AO' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Anguilla', 'AI' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Antarctica', 'AQ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Antigua and Barbuda', 'AG' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Argentina', 'AR' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Armenia', 'AM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Aruba', 'AW' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Australia', 'AU' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Austria', 'AT' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Azerbaijan', 'AZ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Bahamas', 'BS' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Bahrain', 'BH' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Bangladesh', 'BD' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Barbados', 'BB' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Belarus', 'BY' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Belgium', 'BE' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Belize', 'BZ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Benin', 'BJ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Bermuda', 'BM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Bhutan', 'BT' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Bosnia and Herzegovina', 'BA' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Botswana', 'BW' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Bouvet Island', 'BV' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Brazil', 'BR' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('British Indian Ocean Territory', 'IO' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Brunei Darussalam', 'BN' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Bulgaria', 'BG' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Burkina Faso', 'BF' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Burundi', 'BI' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Cambodia', 'KH' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Cameroon', 'CM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Canada', 'CA' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Cape Verde', 'CV' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Cayman Islands', 'KY' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Central African Republic', 'CF' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Chad', 'TD' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Chile', 'CL' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('China', 'CN' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Christmas Island', 'CX' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Cocos (Keeling) Islands', 'CC' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Colombia', 'CO' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Comoros', 'KM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Congo', 'CG' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Cook Islands', 'CK' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Costa Rica', 'CR' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Croatia', 'HR' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Cuba', 'CU' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Cyprus', 'CY' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Czech Republic', 'CZ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Denmark', 'DK' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Djibouti', 'DJ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Dominica', 'DM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Dominican Republic', 'DO',  1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Ecuador', 'EC' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('El Salvador', 'SV' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Equatorial Guinea', 'GQ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Eritrea', 'ER' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Estonia', 'EE' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Ethiopia', 'ET' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Falkland Islands (Malvinas)' ,'FK' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Faroe Islands', 'FO' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Fiji', 'FJ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Finland', 'FI' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('France', 'FR' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('French Guiana', 'GF' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('French Polynesia', 'PF' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('French Southern Territories', 'TF' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Gabon', 'GA' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Gambia', 'GM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Georgia', 'GE' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Germany', 'DE' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Ghana', 'GH' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Gibraltar', 'GI' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Greece', 'GR' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Greenland', 'GL' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Grenada', 'GD' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Guadeloupe', 'GP' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Guam', 'GU' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Guatemala', 'GT' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Guernsey', 'GG' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Guinea', 'GN' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Guinea-Bissau', 'GW' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Guyana', 'GY' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Haiti', 'HT' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Heard Island and McDonald Islands', 'HM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Holy See (Vatican City State)' ,'VA' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Honduras', 'HN' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Hong Kong', 'HK' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Hungary', 'HU' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Iceland', 'IS' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('India', 'IN' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Indonesia', 'ID' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Iran', 'IR' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Ireland', 'IE' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Isle of Man', 'IM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Israel', 'IL' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Italy', 'IT' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Jamaica', 'JM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Japan', 'JP' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Jersey', 'JE' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Kazakhstan', 'KZ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Kenya', 'KE' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Kiribati', 'KI' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Kuwait', 'KW' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Kyrgyzstan', 'KG' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Lao Peoples Democratic Republic', 'LA' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Latvia', 'LV' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Lesotho', 'LS' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Liberia', 'LR' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Libya', 'LY' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Liechtenstein', 'LI' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Lithuania', 'LT' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Luxembourg', 'LU' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Macao', 'MO' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Madagascar', 'MG' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Malawi', 'MW' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Malaysia', 'MY' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Maldives', 'MV' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Mali', 'ML' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Malta', 'MT' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Marshall Islands', 'MH' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Martinique', 'MQ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Mauritania', 'MR' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Mauritius', 'MU' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Mayotte', 'YT' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Mexico', 'MX' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Monaco', 'MC' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Mongolia', 'MN' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Montenegro', 'ME' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Montserrat', 'MS' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Morocco', 'MA' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Mozambique', 'MZ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Myanmar', 'MM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Namibia', 'NA' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Nauru', 'NR' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Nepal', 'NP' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Netherlands', 'NL' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('New Caledonia', 'NC' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('New Zealand', 'NZ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Nicaragua', 'NI' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Niger', 'NE' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Nigeria', 'NG' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Niue', 'NU' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Norfolk Island', 'NF' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Northern Mariana Islands', 'MP' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Norway', 'NO' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Oman', 'OM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Pakistan', 'PK' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Palau', 'PW' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Panama', 'PA' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Papua New Guinea', 'PG' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Paraguay', 'PY' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Peru', 'PE' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Philippines', 'PH' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Pitcairn', 'PN' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Poland', 'PL' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Portugal', 'PT' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Puerto Rico', 'PR' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Qatar', 'QA' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Romania', 'RO' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Russian Federation', 'RU' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Rwanda', 'RW' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Saint Kitts and Nevis', 'KN' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Saint Lucia', 'LC' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Saint Martin (French part)' ,'MF' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Saint Pierre and Miquelon', 'PM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Saint Vincent and the Grenadines', 'VC' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Samoa', 'WS' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('San Marino', 'SM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Sao Tome and Principe', 'ST' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Saudi Arabia', 'SA' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Senegal', 'SN' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Serbia', 'RS' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Seychelles', 'SC' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Sierra Leone', 'SL' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Singapore', 'SG' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Sint Maarten (Dutch part)' ,'SX' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Slovakia', 'SK' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Slovenia', 'SI' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Solomon Islands', 'SB' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Somalia', 'SO' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('South Africa', 'ZA' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('South Georgia and the South Sandwich Islands', 'GS' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('South Sudan', 'SS' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Spain', 'ES' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Sri Lanka', 'LK' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('State of Palestine', 'PS' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Sudan', 'SD' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Suriname', 'SR' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Svalbard and Jan Mayen', 'SJ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Swaziland', 'SZ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Sweden', 'SE' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Switzerland', 'CH' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Tajikistan', 'TJ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Thailand', 'TH' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Timor-Leste', 'TL' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Togo', 'TG' , 1) ;
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Tokelau', 'TK' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Tonga', 'TO' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Trinidad and Tobago', 'TT' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Tunisia', 'TN' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Turkey', 'TR' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Turkmenistan', 'TM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Turks and Caicos Islands', 'TC' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Tuvalu', 'TV' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Uganda', 'UG' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Ukraine', 'UA' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('United Arab Emirates', 'AE' , 1) ;
INSERT INTO Countries (Name,Code, IsActive) VALUES ('United Kingdom', 'GB' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('United States', 'US' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('United States Minor Outlying Islands', 'UM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Uruguay', 'UY' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Uzbekistan', 'UZ' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Vanuatu', 'VU' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Viet Nam', 'VN' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Wallis and Futuna', 'WF' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Western Sahara', 'EH' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Yemen', 'YE' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Zambia', 'ZM' , 1);
INSERT INTO Countries (Name,Code, IsActive) VALUES ('Zimbabwe', 'ZW' , 1);